version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/playground/vue'
      - '/playground/nuxt3'
      - '/playground/nuxt4'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
    cooldown:
      default-days: 7
    groups:
      npm-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
