// 自動生成ファイル。直接編集禁止。pnpm create-component-d で再生成
export const miComponentList = [
    { name: 'MiAvatar', export: 'MiAvatar', filePath: 'minazuki-ui' },
    { name: 'MiButton', export: 'MiButton', filePath: 'minazuki-ui' },
    { name: 'MiAutocomplete', export: 'MiAutocomplete', filePath: 'minazuki-ui' },
    { name: 'MiCheckbox', export: 'MiCheckbox', filePath: 'minazuki-ui' },
    { name: 'MiCheckboxGroup', export: 'MiCheckboxGroup', filePath: 'minazuki-ui' },
    { name: 'MiField', export: 'MiField', filePath: 'minazuki-ui' },
    { name: 'MiRadio', export: 'MiRadio', filePath: 'minazuki-ui' },
    { name: 'MiRadioGroup', export: 'MiRadioGroup', filePath: 'minazuki-ui' },
    { name: 'MiSelect', export: 'MiSelect', filePath: 'minazuki-ui' },
    { name: 'MiSwitch', export: 'MiSwitch', filePath: 'minazuki-ui' },
    { name: 'MiTextarea', export: 'MiTextarea', filePath: 'minazuki-ui' },
    { name: 'MiAlert', export: 'MiAlert', filePath: 'minazuki-ui' },
    { name: 'MiBadge', export: 'MiBadge', filePath: 'minazuki-ui' },
    { name: 'MiDialog', export: 'MiDialog', filePath: 'minazuki-ui' },
    { name: 'MiDrawer', export: 'MiDrawer', filePath: 'minazuki-ui' },
    { name: 'MiModal', export: 'MiModal', filePath: 'minazuki-ui' },
    { name: 'MiNotificationItem', export: 'MiNotificationItem', filePath: 'minazuki-ui' },
    { name: 'MiNotifications', export: 'MiNotifications', filePath: 'minazuki-ui' },
    { name: 'MiProgress', export: 'MiProgress', filePath: 'minazuki-ui' },
    { name: 'MiRating', export: 'MiRating', filePath: 'minazuki-ui' },
    { name: 'MiFrame', export: 'MiFrame', filePath: 'minazuki-ui' },
    { name: 'MiPictureFrame', export: 'MiPictureFrame', filePath: 'minazuki-ui' },
    { name: 'MiFieldAccordionList', export: 'MiFieldAccordionList', filePath: 'minazuki-ui' },
    { name: 'MiFieldFrame', export: 'MiFieldFrame', filePath: 'minazuki-ui' },
    { name: 'MiInputTextCounter', export: 'MiInputTextCounter', filePath: 'minazuki-ui' },
    { name: 'MiOpacityTransition', export: 'MiOpacityTransition', filePath: 'minazuki-ui' },
    { name: 'MiOpacityTransitionGroup', export: 'MiOpacityTransitionGroup', filePath: 'minazuki-ui' },
    { name: 'MiTeleportRoot', export: 'MiTeleportRoot', filePath: 'minazuki-ui' },
    { name: 'MiTranslateTransition', export: 'MiTranslateTransition', filePath: 'minazuki-ui' },
    { name: 'MiTranslateTransitionGroup', export: 'MiTranslateTransitionGroup', filePath: 'minazuki-ui' },
    { name: 'MiBottomNav', export: 'MiBottomNav', filePath: 'minazuki-ui' },
    { name: 'MiBreadcrumb', export: 'MiBreadcrumb', filePath: 'minazuki-ui' },
    { name: 'MiPagination', export: 'MiPagination', filePath: 'minazuki-ui' },
    { name: 'MiStep', export: 'MiStep', filePath: 'minazuki-ui' },
    { name: 'MiTab', export: 'MiTab', filePath: 'minazuki-ui' },
] as const;
