name: Check Version Updated

on:
  push
  # push:
    # branches: [develop]

jobs:
  version_diff:
    runs-on: ubuntu-latest
    outputs:
      chagned: ${{ steps.get_diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        run: git fetch origin ${{ github.base_ref }} --depth=1
        id: get_diff
        run: echo "changed=$(git diff origin/${{ github.base_ref }} HEAD --relative "./package.json" | grep "^+.\+version" | wc -l)" >> $GITHUB_OUTPUT
  version_check:
    runs-on: ubuntu-latest
    needs: [version_diff]
    if: needs.version_diff.outputs.chagned == '0'
    run: |
           echo "::error::package.json version update required."
           exit 1
