name: Release Staging

on:
    push:
        branches: [develop]

env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_USERNAME: DeployBot
    SLACK_CHANNEL: github notify
    SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'

jobs:
    develop2mainPR:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Ruby 3.1
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.1
            - name: Create a release pull request
              env:
                  GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_PR_RELEASE_BRANCH_PRODUCTION: master
                  GIT_PR_RELEASE_BRANCH_STAGING: develop
                  GIT_PR_RELEASE_LABELS: release
                  GIT_PR_RELEASE_TEMPLATE: '.github/.git-pr-release-template'
              run: |
                  gem install git-pr-release -v "1.9.0"
                  git-pr-release --no-fetch || echo "Done."
