name: Create Release PR

on:
  push:
    branches: [develop]

jobs:
  develop2mainPR:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: tokenの設定
        run: |
          echo GH_TOKEN=${{ steps.generate_token.outputs.token }} >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ env.GH_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: '.github/.git-pr-release-template'
        run: |
          gem install git-pr-release -v "1.9.0"
          git-pr-release --no-fetch || echo "Done."
