name: Create Release PR

on:
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  develop2mainPR:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: 3.1
          working-directory: .github
          bundler-cache: true
      - name: Create a release pull request
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/.github/Gemfile
          GIT_PR_RELEASE_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: '.github/.git-pr-release-template'
        run: bundle exec git-pr-release --no-fetch || echo "Done."
