name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main]
permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        env:
          COREPACK_INTEGRITY_KEYS: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Build
        run: pnpm build
