name: Check the source code
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.draft == false && github.base_ref == 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        env:
          COREPACK_INTEGRITY_KEYS: 0

      - name: Enable corepack
        run: |
          npm install -g corepack@latest
          corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run Build
        run: pnpm build

  lint:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        env:
          COREPACK_INTEGRITY_KEYS: 0

      - name: Enable corepack
        run: |
          npm install -g corepack@latest
          corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run linter
        run: pnpm lint
