name: Check the source code
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: npm module install
        run: pnpm i --frozen-lockfile

      - name: Run Build
        run: pnpm build

      - name: Run linter
        run: pnpm lint
