name: Test & Coverage

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        env:
          COREPACK_INTEGRITY_KEYS: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          files: test-results/junit.xml

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@3c054a2d2e2ca45446417ad5d6d5eb33092af8f1 # v2.12.1
        if: always()
